### PR TITLE
Add a simple static analysis workflow

### PR DESCRIPTION
**Pull request by Jacalz**
This basically just copies the one from Fyne. We might want this before we start merging large PRs.

### CODE REVIEW

**Comment by Jacalz** [comment]
This is far from perfect. Gocyclo complains about cyclomatic complexity (one of which can probably be ignored) and staticcheck warns about a deprecated method (https://github.com/Jacalz/glfw-js/runs/6285148965?check_suite_focus=true). I don't really know what to do about these so I'll leave this here for you to decide.

**Comment by Bluebugs** [comment]
The deprecation warning is right, but the point of this binding is to emulate v3, so it is normal that we have the same API as GLFW even if GLFW is marking some of its function as deprecated. Would the warning go away if we marked that API as deprecated in glfw-js too?

**Comment by dominikh** [comment]
If a function is marked as deprecated, then it can use other deprecated API without getting flagged by Staticcheck. But if you have a lot of such functions, it might be more straightforward to just disable that check in the relevant files (see https://staticcheck.io/docs/configuration/#file-based-linter-directives for that.)

**Comment by Jacalz** [comment]
Thanks @dominikh. That works great :+1:

**Comment by Jacalz** [comment]
The static analysis is now passing: https://github.com/Jacalz/glfw-js/actions/runs/2295779197

**Review by andydotxyz — APPROVED** [review]
Looks good to me too - any thoughts @Bluebugs

**Review by Bluebugs — APPROVED** [review]

**Comment by Jacalz** [comment]
Thanks. It’s merged now. Feel free to set the action as required if you want to :)

**Pull request merged**
