### PR TITLE
Remove support for GopherJS

### PR DESCRIPTION
**Pull request by Jacalz**
Modernization and updates to match https://github.com/fyne-io/fyne/pull/4486.

### CODE REVIEW

**Comment by andydotxyz** [comment]
Would it be possible to split the modernisation and GopherJS removal?
They both impact build flags and I think that both happening at the same time has hidden some compile tag option combinations that no longer work correctly.

**Comment by Jacalz** [comment]
I separated some stuff out into https://github.com/fyne-io/glfw-js/pull/16.

**Comment by Jacalz** [comment]
CI seems to be failing because the goimports tool requires Go 1.18 now. Fixed by the other PR...

**Comment by Jacalz** [comment]
I think this should be fine now. Everything is now using `wasm` build tags only.

**Review by andydotxyz — APPROVED** [review]
Yeah looks good

**Pull request merged**
