### PR TITLE
add clipboard support

### PR DESCRIPTION
**Pull request by gcottom**
add clipboard support for both gopherjs and wasm.

### CODE REVIEW

**Comment by andydotxyz** [comment]
Thanks so much for this. Do you have a suggestion on how it can be tested ?

**Comment by gcottom** [comment]
The testing that I did for this was with the fyne demo application. I set the go.mod in the demo application to utilize my local copy of glfw-js. Then went to the widgets demo and was able to copy/paste text in the entry widgets. I believe to test the clipboard functionality with a unit test, we will need to include another module that handles clipboard functionality. But with clipboard being platform dependent, that test may be a bit faulty. I'm just a bit hesitant when it comes to adding dependency bulk.

**Comment by rmasci** [comment]
I tried by first git clone https://github.com/gcottom/glfw-js.git
Then in my  In my go.mod I used a line that looked like this:
```
 replace github.com/fyne-io/glfw-js => /Users/rmasci/go/src/github.com/gcottom/glfw-js
```
I built a test application and I couldn't cut and paste.

**Comment by gcottom** [comment]
@rmasci were you using the keyboard shortcuts or the dialog menu? I've noticed that the cmd key doesn't work in the fyne web context on mac. But I can use the ctrl key and it works like the control key on windows. I tested this in chrome and safari on Sonoma. Looking into the console log it looks like it could be firefox issue where permissions are not requested to read the clipboard. I have an idea of where to start.

**Comment by gcottom** [comment]
So from what I've been able to figure out, Firefox is just plain difficult. They don't support reading from the clipboard in most situations and want to require an extension to enable reading from the clipboard. Looks like it's a security/privacy feature. Please see the link for Browser clipboard support. [Browser Clipboad API Compatibility](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard#browser_compatibility)

**Comment by rmasci** [comment]
True cut and paste using shortcuts doesn't work. And certainly not in
firefox and I suspected it was firefox's fault.  Works fine in Edge.  If
others want I put a sample json editor app I built while learning Fyne, I
have instructions on how to use github.com/gcottom/glfw-js. You can find it
here:
https://github.com/rmasci/jsonedit

Simple app, but you can play with the cut and paste, or at least I was able
to :)

**Comment by gcottom** [comment]
I have opened a separate PR for shortcut keys on Mac. See [PR](https://github.com/fyne-io/glfw-js/pull/14)

**Comment by gcottom** [comment]
PR for the mac keyboard shortcuts is submitted to the main fyne repo. [Fyne PR 4348](https://github.com/fyne-io/fyne/pull/4348). Do we have any next steps?

**Review by andydotxyz — APPROVED** [review]
Excellent thanks

**Comment by andydotxyz** [comment]
This sat for long enough without request for change, I think it can be landed.

**Pull request merged**
