### PR TITLE
Fix Shortcut Key (CMD) Mac

### PR DESCRIPTION
**Pull request by gcottom**
When using a Mac keyboard layout, the CMD key is not performing the shortcut key action. That is because we interpret the Meta key/Super key/cmd key as if it was a windows keyboard windows key. This fix attempts to address the issue by adding the user agent string to the window struct and then accessing it when checking key modifier. If the user agent contains "mac" we should interpret the meta key as the default shortcut key. This is achieved by changing the mods value from ModSuper to ModControl, when we are using a mac user agent. This change further enhances changes [here](https://github.com/fyne-io/glfw-js/pull/13). This can be tested by using any demo app with a text input widget such as widget.Entry, setting focus on that widget, typing a few characters, and using the keyboard shortcut CMD-a. Before this change nothing would happen. After this change, the shortcut will select all of the text in the widget. I've tested on Chrome, Firefox, Edge, Opera, and Safari on an m2 Mac.

### CODE REVIEW

**Review by andydotxyz — COMMENTED** [review]
I don't agree with this change. macOS devices have command and control keys - one does not simply replace the other.

It's up to the toolkit to interpret the keys to set up the shortcuts

**Comment by andydotxyz** [comment]
The change required for fyne to cmd+c copy to clipboard with JavaScript is in the fyne web driver code.

Consider a terminal app - pressing cmd+c must copy, but on a windows/Linux terminal it is control+shift+c. With this change you would end up terminating the app instead.

Look into the toolkit and see how we have a "default modifier". This maps to ctrl on windows/Linux and command on macOS for the expected consistency where appropriate. If you translate at the event layer this is not possible.

**Comment by gcottom** [comment]
Thanks @andydotxyz, I think I see another way to do this better. Fyne has two files at the root called key_darwin.go and key_other.go. These set the default shortcut key based on build constraints. What I’m thinking here is that we can set the shortcut key based on value of navigator.platform, navigator.appversion, or navigator.useragent. That way there’s no overriding of mod key values. Then we should be able to use shortcuts as they would normally work on a non web build.

**Comment by andydotxyz** [comment]
Yes toggling the default should work ok. As long as the true keyboard info is still being sent through.
The challenge as you say is that browser.OS is more complex than runtime.GOOS.

**Pull request closed without merging**
