### PR TITLE
Start adding the Window API, with stubs for the browser

### PR DESCRIPTION
**Pull request by samhocevar**

### CODE REVIEW

**Comment by Bluebugs** [comment]
Could you explain your plan for this API, I am not sure they will be that useful in the web context.

**Comment by samhocevar** [comment]
I am porting an application (https://github.com/ikemen-engine/Ikemen-GO) to WebGL / mobile and it makes use of this API. If it’s not provided by the isomorphic glfw, the client application has to write its own wrappers in a `go:build js` file, defeating the purpose of this library. Do I misunderstand the purpose of this library?

**Comment by Bluebugs** [comment]
Absolutely. Sorry, my question was a bit unclear. Do you think or did you already have an idea on how to implement those function? Or do you think they will stay as empty place holder just for linking purpose and that will be ok for the user of the api?

**Comment by samhocevar** [comment]
Ah, I understand. Here’s how I see it:
 - `SetAttrib()` will probably remain a stub, though I haven’t thought about each and every of them. But the most likely to be implemented are those related to the rendering context, and I think after `newContext()` has been called it’s too late for `SetAttrib()`.
 - `SetMonitor()` will most certainly remain a stub; the browser only abstracts one monitor 
 - `SetIcon()` may be implemented: it is possible to manipulate the DOM in order to change the favicon (though it’s unclear to me if the image data can be inlined rather than using a link)

**Review by Bluebugs — APPROVED** [review]

**Comment by Bluebugs** [comment]
Thanks for your explanation. I can see how the one that are not printing anything are most likely to stay stub and the one that do print something might maybe be implemented. Let's go with that.

**Pull request merged**
